Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :edit, :create, :update, :destroy]

  resources :notes, only: [:show, :new, :edit, :update, :create, :destroy]
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/models/Album.rb
class Album < ApplicationRecord
  ACCEPTED_STATUS = ["studio", "live"]

  validates :title, presence: true, uniqueness:true
  validates :band_id, presence: true
  validates :status, presence: true, inclusion: ACCEPTED_STATUS
  validates :year, presence: true

    belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: "Band"

    has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: "Track",
    dependent: :destroy
    
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id]) 
    render :show
  end

  def new
    if params.has_key?(:band_id)
      @band = Band.find(params[:band_id])
      @album = Album.new
      render :new
    else
      @album = Album.new
      render :new
    end
  end

  def index
    @albums = Album.all
    render :index
  end

  def create
    new_p = wanted_params
    new_p[:album][:year] = new_p[:album][:year].to_i
    @album = Album.create(new_p)
    if @album
      redirect_to album_url(@album)
    else
      render json: Album.errors.full_messages , status: :unprocessable_entity
    end
  end

  def destroy
    album = Album.find(params[:id])
    band = album.band 
    album.destroy
    redirect_to band_url(band)
  end

  def edit
    @album = Album.find(params[:id])
    @band = @album.band
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    
    if @album
      @album.update(wanted_params)
      redirect_to album_url(@album)
    else
      render json: Album.errors.full_messages , status: :unprocessable_entity
    end
  end

  private

  def wanted_params
    params.require(:album).permit(:title, :year, :status, :band_id)
  end
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/albums/_form.html.erb
<% action = album.persisted? ? album_url(album) : albums_url %>
<% method = album.persisted? ? "PATCH" : "POST" %>

<div class="new_album">
  
    <% if method == "POST"%>
      <p>Let us enter an album</p>
    <% else %>
      <p>Lets edit <%= album.title %></p>
    <% end %>

    <br>
    
    <form action="<%= action %>" method="POST">
    <input type="hidden" name="_method" value="<%= method %>">
      <%= auth_token %>

      <label for="Album_t">Album Title: </label>
      <input id="Album_t" name="album[title] type="text" value="<%= album.title %>">

      <label for="band_name">Band Names</label>
      <select id="band_name" name="album[band_id]">
        <% Band.all.each do |bd| %>
          <option value="<%= bd.id%>" <%= band == bd ? "selected" : ""%> ><%= bd.name %><option>
        <% end %>
        
      </select>

        <label>Album-Condition: </label>
        <label for="s_state">Studio</label>
        <input
         id="s_state" 
         type="radio" 
         name="album[status]" 
         value="studio" 
         <%= album.status == "studio" ? "checked" : "" %>>
        <label for="l_state">Live</label>
        <input 
        id="l_state" 
        type="radio" 
        name="album[status]" 
        value="live" 
        <%= album.status == "live" ? "checked" : "" %>>

        <label for="year">Year</label>
        <input id="year" type="text" name="album[year]" value="<%= album.year.to_s %>"> 

      <input type="submit" value="Enter-Form">
    </form>

</div>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/albums/edit.html.erb
<%= render 'form', album: @album, band: @band %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/albums/new.html.erb
<%= render 'form', album: @album, band: @band %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/albums/show.html.erb
<div class="show_album">

  <h2><%=@album.title%><h/2>

  <br>

  <%= link_to "Edit-Album", edit_album_url%>

  <br>

    <ol>
      <% @album.tracks.each do |trk| %>
        <li><%= trk.title %> 
        <%= link_to "Edit-Track-Info", edit_track_url(trk.id) %>
        <%= link_to "Show-Notes", note_url(trk) %>
        </li>
      <% end %>
    </ol>

  <br>

      <%= link_to "Add-Track", new_album_track_url(@album) %>

  <% band = @album.band %>
  <%= link_to "band-page", band_url(band.id)%>
</div>