Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :edit, :create, :update, :destroy]

  resources :notes, only: [:show, :new, :edit, :update, :create, :destroy]
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLabel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">

      header {
        display: flex;
        justify-content: space-between;
      }


    </style>
  </head>
  
  <body>

    <header>
    
      <h1>Music App</h1>
      <nav>
        <% if current_user.nil? %>
          <a href="<%= new_session_url %>">Sign in</a>
          or
          <a href="<%= new_user_url %>">Sign up</a>
        <% else %>
          <%= current_user.email %>
          <%= button_to "Log-Out", session_url, method: :delete %>
        <% end %>
      </nav> 

    </header>

    <%= yield %>
  </body>

  <footer>
    <p> Welcome to Sabit's Band-site :)</p>
    <%= yield :footer %>    
  </footer>
</html>