Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :edit, :create, :update, :destroy]

  resources :notes, only: [:show, :new, :edit, :update, :create, :destroy]
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/models/Band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: 'Album',
  dependent: :destroy
  
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/controllers/bands_controller.rb
class BandsController < ApplicationController
before_action :restrict_non_logged_usr, only: [:index, :new, :edit]

  def show
    @band = Band.find(params[:id]) 
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.create(wanted_params)
    if @band
      redirect_to band_url(@band)
    else
      render json: Band.errors.full_messages , status: :unprocessable_entity
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.nil? ? true : band.destroy
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band
      @band.update(wanted_params)
      redirect_to band_url(@band)
    else
      render json: Band.errors.full_messages , status: :unprocessable_entity
    end
  end

  private

  def wanted_params
    params.require(:band).permit(:name)
  end
end

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% method_vrb = band.persisted? ? "PATCH" : "POST" %>

<div>
  <h2>
    <% if method_vrb == "POST" %>
      New Band Entry
    <% else %>
      Edit You Band Information
    <% end %>
  </h2>

  <form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%=method_vrb%>">
  <%= auth_token %>

    <label for="name">Band Name</label>
    <input id="name" type="text" name="band[name]" value="<%= band.name %>">

    <input type="submit" value="Submit">
  </form>
</div>

<%= content_for :footer do %>
  <% if method_vrb == "POST" %>
    <p>Please review date before submission!</p>
  <% else %>
    <p>Review your corrections please!</p>
  <%end%>
<% end %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/bands/edit.html.erb
<%= render 'form', band: @band %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/bands/index.html.erb
<div>
  <% if current_user%>
    <h2>Welcome <%= current_user.email %></h2>
  <% end %>

  <ul>
    <% @bands.each do |band| %>
      <li><%= link_to band.name, band_url(band) %></li>
    <% end %>
   </ul> 
</div>

<%= content_for :footer do %>
  <p>I proudly present you with these wonderful bands :)</p>
<% end %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/bands/new.html.erb
<%= render 'form', band: @band %>

Immersive_Course_Folders/W4/RecordLabel-Site/MusicLabel/app/views/bands/show.html.erb
<div class="show_band">
  
  <% albums = @band.albums %>

    <label for="albums">Albums by <%= @band.name%></label>
    <ul id="albums">
      <% albums.each do |al| %>
      <li><%= link_to al.title, album_url(al) %></li>
      <%= button_to "Remove-Album?", album_url(al), method: :delete %>
      <% end %>
    </ul>

    <%= link_to "Register-New-Album", new_band_album_url(@band)%>
</div>

<%= content_for :footer do %>
  <p>I will eventually output stats pertaining to the given band here</p>
<% end %>