Immersive_Course_Folders/w5/D2FinalRbProj/MyReddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'
  resources :static_pages, only: [:root]

  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]

  resources :subs, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :posts, only: [:new, :edit, :show]
  end

  resources :posts, only: [:show, :create, :update, :destroy] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:index, :new, :create, :show]
  
  resource :session, only: [:new, :create, :destroy]
end

Immersive_Course_Folders/w5/D2FinalRbProj/MyReddit/app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, :author_id, :post_id, presence: true

    belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User'
    
    belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: 'Post'

    has_many :child_comments,
    primary_key: :id,
    foreign_key: :p_comment_id,
    class_name: 'Comment',
    dependent: :destroy

end

Immersive_Course_Folders/w5/D2FinalRbProj/MyReddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
        post, parentCmt = nil
        
        if params[:post]
            post = Post.find(params[:post])
        end
        if params[:pCmt]
            parentCmt = Comment.find(params[:pCmt])
        end
        @athrName = []
            if parentCmt
                parentCmt.child_comments.each { |cmt| @athrName.push(cmt.author.name) }
            end
        
        @comments = post.comments.where(p_comment_id: nil) if post
        
        if post
            respond_to do |format|
                format.json { render :index }
            end
        elsif parentCmt
            respond_to do |format|
                format.json { render :athr_nms }
            end
        else
            respond_to do |format|
                format.json { render json: post.errors.full_messages, status: 422 }
            end
        end
    end

    def show
        @comment = Comment.find(params[:id])
        render :show
    end

    def new
        @post = Post.find(params[:post_id])
        render :new
    end

    def create
        @comment = Comment.new(wanted_params)
        if @comment.save!
            respond_to do |format|
                format.json { render :show }
            end
        else
            respond_to do |format|
                format.json { render json: @comment.errors.full_messages, status: 422 } 
            end
        end
    end

    private

    def wanted_params
        params[:comment].permit(:post_id, :author_id, :content, :p_comment_id)
    end
end

Immersive_Course_Folders/w5/D2FinalRbProj/MyReddit/app/views/comments/new.html.erb
<Form action="<%= comments_url %>" method="POST" >
    <%= auth_token %>

    <textarea name="comment[content]">
    </textarea>

    <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
    <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">

    <input type="submit" value="POST">
</Form>

<a href="<%= post_url(@post) %>">Return-to-Post</a>

Immersive_Course_Folders/w5/D2FinalRbProj/MyReddit/app/views/comments/show.html.erb
<h2>Reply to this Comment</h2
<br>
<a href="<%= post_url(@comment.post_id) %>">Return-to-Post</a>

<section class="parent-comment-sec">
    <ul>
    <% Comment.where(p_comment_id: @comment.id).each do |cm| %>
        <li><%= cm.content %></li>
    <% end %>
    </ul>
</section>

<form action="<%= comments_url %>" method="POST" >
    <%= auth_token %>

    <textarea name="comment[content]">
    </textarea>

    <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">

    <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">
    
    <input type="hidden" name="comment[p_comment_id]" value="<%= @comment.id %>">
    <input type="submit" value="POST">
</form>